version: "3"
services:
# Bando de dados postgres auth-db
  auth-db:
    image: postgres:13
    container_name: auth-db 
    restart: always
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5434:5432

# Bando de dados postgres product-db  
  product-db:
    image: postgres:13
    container_name: product-db 
    restart: always
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5435:5432

# Bando de dados (mongodb) sales-db
  sales-db:
    image: mongo
    container_name: sales-db 
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=sales-db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
      - 28017:28017

#  Api auth-api
  auth-api:
    build: './auth-api'
    container_name: auth-api
    environment:
      - PORT=8080
    ports:
      - 8080:8080
#  Api product-api
  product-api:
    build: './product-api'
    container_name: product-api
    environment:
      - PORT=8081
    ports:
      - 8081:8081
#  Api sales-api
  sales-api:
    build: './sales-api'
    container_name: sales-api
    environment:
      - PORT=8082
    ports:
      - 8082:8082
# RabbitMQ 
  sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit 
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672