INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'HARDWARE','hardwares',1, NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'PERIFÉRICOS','periféricos',1, NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'COMPUTADORES','computadores',1, NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'GAMES','hardware',1, NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'CELULARES & SMARTPHONES','celulares-smartphones',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'TV','TV',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'AUDIO','audio',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'PROJETORES','projetores',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'ESPAÇO GAMER','espaço-gamer',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'ESCRITORIO','escritorio',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'CASA INTELIGENTE','casa-inteligente',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'TABLETS-IPAD E-READERS','tablets-ipad-e-readers',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'CÂMERAS E DRONES','cameras-e-drones',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'ENERGIA','energia',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'CONECTIVIDADE','conectividade',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'GEEK','geek',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'ELETRODOMÉSTICOS','eletrodomesticos',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'ELETROPORTÁTEIS','eletroportateis',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'AR E VENTILAÇÃO','ar-e-ventilacao',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'SEGURANÇA','seguranca',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'AUTOMAÇÃO','automacao',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'TELEFONIA FIXA','telefonia-fixa',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'ROBÓTICA','robotica',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'SERVIÇOS DIGITAIS','serviços-digitais',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'BENEFICIOS','beneficios',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'MODAS','modas',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'FERRAMENTAS','ferramentas',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'CUIDADOS PESSOAIS','cuidados-pessoais',1,NOW())
INSERT INTO CATEGORIES_MAIN (ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_categories_main_id'),'SMART HOME','smart-home',1,NOW())





INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'NOTEBOOKS','notebooks',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),6,'CELULARES','celulares',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'MOUSES GAMER','mouses-gamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'TECLADOS','teclados',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'SOFTWARES','softwares',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'PC','pc',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'MONITORES','monitores',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'IMPRESSORAS','impressoras',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'SCANNERS','scanners',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'TECLADO GAMER','teclado-gamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'CAIXA DE SOM','caixa-de-som',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'HEADSETS','headsets',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'MOUSE PAD','mouse-pad',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'ÓCULOS','oculos',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'CABOS E ADAPTADORES','cabos-e-adaptadores',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'FONES DE OUVIDOS GAMER','fones-de-ouvidos-gamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'KIT GAMER','kit-gamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'STREAMER','streamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'HEADSET GAMER','headset-gamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'MESA DIGITALIZADORA','mesa-digitalizadora',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'PEN DRIVE','pen-drive',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'GABINETES','gabinetes',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'SUPRIMENTOS','suprimentos',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'TECLADO E MOUSE','teclado-mouse',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),3,'SUPORTES','suportes',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),4,'SIMULADORES','simuladores',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),4,'XBOX','xbox',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),4,'PLAYSTATION','playstation',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),4,'NITENDO','nitendo',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),4,'VIDEO GAME RETRO','video-game-retro',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),4,'ACESSÓRIOS GAMER','acessorios-games',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),4,'PORTÁTEIS','portateis',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),6,'SMARTPHONES','smartphones',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),6,'CELULAR BÁSICO','celular-básico',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),6,'SMARTPHONES WEARABLES','smartphone-wearables',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),6,'ACESSÓRIOS PARA SMARTPHONES','acessorios-para-smartphones',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'SSD','ssd',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),1,'KIT-HARDWARE','kit-hardware',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'PLACAS INTERFACE','placas-interface',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'COOLERS','coolers',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'DISCO RIGIDO (HD)','disco-rigido-hd',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'DRIVES','drives',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'FONTES','fontes',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'MEMÓRIA RAM','memoria-ram',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'PLACA DE VIDEO (VGA)','placa-de-video-vga',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'PLACAS-MÃE','placas-mãe',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'PROCESSADORES','processadores',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'CADEIRAS GAMER','cadeiras-gamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'MESA GAMER','mesa-gamer',1, NOW())
INSERT INTO CATEGORIES (ID,MAIN_ID,NAME,META_LINK,ACTIVE, CREATED_AT) VALUES (nextval('sequence_category_id'),5,'TAPETE GAMER','tapete-gamer',1, NOW())


